name: GitHub Actions
on: [push, pull_request]

env:
  REGISTRY: vasilikul
  IMAGE_NAME: new-fastapi-weather-app

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event == 'merge'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.4"
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Run unit tests
        run: pytest

  build_and_push:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7) .

      - name: Lok in DockerHub
        run: docker login -u ${{ secrets.DOCKER_HUB_LOGIN }}  -p ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push new version to DockerHub
        run: docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)
